### PR TITLE
[Resolves #602] move sceptre-ssm-resolver

### PR DESCRIPTION
**Pull request by zaro0508**
Move the sceptre-ssm-resolver from https://github.com/zaro0508/sceptre-ssm-resolver
to the official Sceptre github Org.  It's been slightly refactored
to include unit tests.  This resolves sceptre issue https://github.com/Sceptre/sceptre/issues/602

### CODE REVIEW

**Comment by zaro0508** [comment]
@ngfgrant Do we need to enable circleci for new projects?  if so how is that done?

**Comment by ngfgrant** [comment]
Yeh I’ve added it now thanks

**Comment by zaro0508** [comment]
@ngfgrant CircleCI is not getting triggered? Is there something else we need to get it working?

**Comment by zaro0508** [comment]
CircleCi not triggering with this PR,  replacing it with PR #2

**Pull request closed without merging**
